baseURL: "https://shirazlug.ir/"

languageCode: "fa-IR"
title: "وب‌سایت رسمی شیرازلاگ (گروه کاربران گنو/لینوکس شیراز)"
theme: hugo-refresh-rtl
staticDir: "static"

#disableKinds: ["taxonomy", "taxonomyTerm", "RSS", "sitemap"] 404 on tags
disableKinds: ["taxonomyTerm", "RSS"]

#blackfriday:
#  hrefTargetBlank: true

# Options for rendering HTML from markdown
# NOTE : This is configuration for syntax highlighting in its new format. For some reason hugu renders this website with old 'pygments'
# renderer, so it only accepts legacy configuration items.
#markup:
#  highlight:
#    codeFences: true
#    guessSyntax: false
#    lineNoStart: 1
#    lineNos: false
#    lineNumbersInTable: true
#    noClasses: false
#    tabWidth: 4

# Legacy configuration for syntax highlighting
pygmentsUseClasses: true
pygmentsCodeFences: true

Taxonomies:
  tag: "tags"

enableRobotsTXT: True

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

googleAnalytics: UA-165578778-1

# Supported fonts are:
# https://fonts.google.com/

params:
  # parameter used to specify if you want to minify the imported js
  jsMinify: true
  # parameter used to specify if you want to add the fingerprint to the imported js
  jsFingerprint: true
  # parameter used to specify if you want to minify the imported css
  cssMinify: true
  # parameter used to specify if you want to add the fingerprint to the imported css
  cssFingerprint: true
  # option to specify the main colour of the theme
  mainColour: "#F39200"
  author: "شیرازلاگ"
  favicon: "favicon.ico"
  sitename: "Shirazlug"
  # google_tag_manager : GTM-MF668L5
  

  # summary options
  summary:    
    # option to specify the default image in the summary list
    defaultImage : "img/posters/default_poster.jpg"
  
  # loading options
  loading:
    # option to specify the loading image
    image: "images/rings.svg"

  # main pages options
  mainPage:
    # option to specify the main font of the theme
    fontFamily: "Shabnam" 

  # sidebar options
  sidebar:
    # option to specify the logo of the sidebar
    logo: "logo/shirazlug_white.png"
    # logo: "img/shirazlug_logo.svg"
    # option to specify the font of the sidebar
    fontFamily: "Shabnam"
    tags: "همه برچسب‌ها"

  # navbar options
  navbar:
    fontFamily: "Shabnam" 
    tags: "برچسب‌ها"
    menu: [
      
      {
        name: "home",
        title: "خانه",
        url: "/",
        weight: 8,
        icon: 'home'
      }, 
      {
        name: "sessions",
        title: "جلسه‌های لاگ",
        url: "/sessions/",
        weight: 7,
        icon: 'th-list'
      },
      {
        name: "posts",
        title: "پست‌های آزاد",
        url: "/posts/",
        weight: 6,
        icon: 'clipboard'
      },      
      {
        name: "events",
        title: "رویدادها",
        url: "/events/",
        weight: 5,
        icon: 'calendar'
      },
      {
        name: "news",
        title: "اخبار",
        url: "/news/",
        weight: 4,
        icon: 'rss'
      },
      {
        name: "team",
        title: "تیم اجرایی",
        url: "/team/",
        weight: 3,
        icon: 'users'
      },
      {
        name: "about",
        title: "درباره ما",
        url: "/about/",
        weight: 2,
        icon: 'info'
      },      
      {
        name: "links",
        title: "لینک‌های مفید",
        url: "/links/",
        weight: 1,
        icon: 'link'
      },
     
    ]
  
  # 404 page options
  pagNotFound:
    # option to specify the main picture of the sidebar
    image: "logo/404.svg"
    # option to specify the title of the 404 page
    title: خطای ۴۰۴
    # option to specify the subtitle of the 404 page
    subtitle: صفحه مورد نظر شما یافت نشد
    # option to specify the width of the image in the 404 page
    imageWidth: 500px

  # homepage options
  homepage:
    # option to specify the title in the homepage
    title: "شیرازلاگ"    
    # option to specify the subtitle in the homepage
    subtitle: " (گروه کاربران لینوکس شیراز) "
    description: "به شیرازلاگ خوش آمدید :) لاگ به معنی گروه کاربران گنو/لینوکس است و از افراد مختلف که به منظور تبادل اطلاعات در حوزه‌ی نرم‌افزارهای آزاد و متن‌باز دور هم جمع می‌شوند، تشکیل شده است. اگر تمایل دارید دانش خود را با دیگران به اشتراک بگذارید یا کنجکاوید تا از تکنولوژی‌های آزاد جدید اطلاعاتی کسب کنید و یا از بودن در کنار چند دوست فعال در این زمینه لذت می‌برید، با ما همراه شوید. در ضمن، شرکت در جلسات برای عموم آزاد و رایگان است."
    # Logo
    logo: "logo/shirazlug.svg"

    # Last Session Details
    lastSessionPoster: "img/posters/poster194.jpg"
    lastSessionAlt: "آشنایی با الکترون جهت طراحی اپلیکیشن"

    # Next Session
    # TODO Make this property true whenever subject, date, time, and place of next session are determined
    certainNextSession: true
    nextSessionPoster: "img/posters/poster195.jpg"
    nextSessionAlt: "میکروسرویس‌ها در پایتون"
    
    # link: "https://evnd.co/9qWYn"
    imageWidth: 500px
    # lastSession: session194
    # Address
    # address: "آدرس: خ همت جنوبی، کوچه ۱۰/۲، سالن همایش امام رضا (ع)"
    # address: "آدرس: ستارخان، انتهای خ نمازی، دانشگاه زند، سالن همایش"
    # address: "آدرس: بولوار مدرس، روبروی فضل‌آباد، دانشگاه صنعتی شیراز - خانه فرهنگ"
    # address: "شیراز، میدان آزادی، پارک آزادی"
    # address: "شیراز، بولوار امیرکبیر، بوستان جنت"
    # nextSessionProspect: به دلیل تعطیلات عید نوروز تا ۱۵ فروردین ۱۳۹۹ جلسه ای نداریم
    # Or you can use this:
    # nextSessionProspect: موضوع، زمان و مکان جلسهٔ آیندهٔ شیرازلاگ هنوز مشخص نشده است؛ ولی اگر همه چیز مانند روال سابق پیش برود این جلسه در تاریخ چند شنبه ۹۹ ماه ۱۳۹۹ برگزار خواهد شد.
    

  section:
    fontFamily: "Shabnam"

  # footer options
  footer:
    fontFamily: "Shabnam"
    logo: "logo/shirazlug_white.svg"   
    copyright: "۱۳۹۸،۱۳۹۹ - شیرازلاگ"
    social: [
      {
        title: "contact@shirazlug.ir",
        icon: "fas fa-envelope",
        url: "mailto:contact@shirazlug.ir",
        weight: 6
      },
      {
        title: "shirazlug",
        icon: "fab fa-telegram",
        url: "https://t.me/shirazlug",
        weight: 5
      },
      {
        title: "shirazlug.ir",
        icon: "fab fa-instagram",
        url: "https://www.instagram.com/ShirazLUG.ir/",
        weight: 4
      },
      {
        title: "shirazlug_ir",
        icon: "fab fa-twitter",
        url: "https://twitter.com/ShirazLUG_ir",
        weight: 3
      },
      {
        title: "shirazlug",
        icon: "fab fa-linkedin",
        url: "https://www.linkedin.com/in/shirazlug/",
        weight: 2
      },
      {
        title: "shirazlug",
        icon: "fab fa-gitlab",
        url: "https://framagit.org/shirazlug",
        weight: 1
      }
    ]

